# Generated by Django 2.0.3 on 2018-03-29 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razaosocial', models.CharField(max_length=100, verbose_name='Razão Social')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=2, verbose_name='Série')),
                ('numero', models.CharField(max_length=5, verbose_name='Número')),
                ('nomedescricao', models.CharField(max_length=100, verbose_name='Nome/Descrição')),
                ('peso', models.CharField(max_length=5, verbose_name='Peso')),
                ('cubagem', models.CharField(max_length=5, verbose_name='Cubagem')),
                ('data', models.DateTimeField(verbose_name='Data')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nfapp.Empresa')),
            ],
        ),
    ]
