# Generated by Django 2.0.3 on 2018-03-29 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfapp', '0004_auto_20180329_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='cubagem',
            field=models.CharField(max_length=5, null=True, verbose_name='Cubagem'),
        ),
        migrations.AddField(
            model_name='nota',
            name='data',
            field=models.DateTimeField(null=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='nota',
            name='nomedescricao',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome/Descrição'),
        ),
        migrations.AddField(
            model_name='nota',
            name='numero',
            field=models.CharField(max_length=5, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='nota',
            name='peso',
            field=models.CharField(max_length=5, null=True, verbose_name='Peso'),
        ),
        migrations.AddField(
            model_name='nota',
            name='serie',
            field=models.CharField(max_length=2, null=True, verbose_name='Série'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nfapp.Empresa'),
        ),
    ]
