# Generated by Django 2.0.3 on 2018-03-29 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfapp', '0006_auto_20180329_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=2, null=True, verbose_name='Série')),
                ('numero', models.CharField(max_length=5, null=True, verbose_name='Número')),
                ('nomedescricao', models.CharField(max_length=100, null=True, verbose_name='Nome/Descrição')),
                ('peso', models.CharField(max_length=5, null=True, verbose_name='Peso')),
                ('cubagem', models.CharField(max_length=5, null=True, verbose_name='Cubagem')),
                ('data', models.DateTimeField(null=True, verbose_name='Data')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nfapp.Empresa')),
            ],
        ),
    ]
